### ISSUE TITLE
[User-question]

### ISSUE THREAD

**Issue by wehrend** [tedfelix/rosegarden-official#5]
Hey, I ve found out how to play notes to control a midi device (like the picoadk I am just discovering right now), but I am not sure to play notes live on soft keyboard in rosegarden. So please give me a hint. 
Best,
Sven Wehrend

**Comment by tedfelix** [comment]
Rosegarden does not include a soft keyboard.  I would recommend using vmpk for that.

https://vmpk.sourceforge.io/

To connect Rosegarden to a synth via ALSA MIDI, go to Studio > Manage MIDI Devices.

You might find my tutorial helpful:

http://www.tedfelix.com/linux/linux-midi.html

**Comment by wehrend** [comment]
I'll take a look, many thanks.

Best,
Sven Wehrend
